sudo: required
services:
    - docker

before_install:
    - docker build -t pawel970/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true pawel970/docker-react npm run test -- --coverage   

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-eu-west-1-046361131185"
    backet_path: "docker"
    on:
        branch: master
    
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"

