sudo: required
services:
    - docker

before_install:
    - docker build -t pawel970/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true pawel970/docker-react npm run test -- --coverage   